const sample_food = [
    {
        id: '1',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'images/food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '2',
        name: 'Meatball',
        price: 20,
        cookTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        stars: 4.7,
        imageUrl: 'images/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
    },
    {
        id: '3',
        name: 'Hamburger',
        price: 5,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.5,
        imageUrl: 'images/food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '4',
        name: 'Fried Potatoes',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3.3,
        imageUrl: 'images/food-4.jpg',
        tags: ['FastFood', 'Fry'],
    },
    {
        id: '5',
        name: 'Chicken Soup',
        price: 11,
        cookTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.0,
        imageUrl: 'images/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
    },
    {
        id: '6',
        name: 'Vegetables Pizza',
        price: 9,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'images/food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '7',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'images/food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '8',
        name: 'Meatball',
        price: 20,
        cookTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        stars: 4.7,
        imageUrl: 'images/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
    },
    {
        id: '9',
        name: 'Hamburger',
        price: 5,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.5,
        imageUrl: 'images/food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '10',
        name: 'Fried Potatoes',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3.3,
        imageUrl: 'images/food-4.jpg',
        tags: ['FastFood', 'Fry'],
    },
    {
        id: '11',
        name: 'Chicken Soup',
        price: 11,
        cookTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.0,
        imageUrl: 'images/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
    },
    {
        id: '12',
        name: 'Vegetables Pizza',
        price: 9,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'images/food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '13',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'images/food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '14',
        name: 'Meatball',
        price: 20,
        cookTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        stars: 4.7,
        imageUrl: 'images/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
    },
    {
        id: '15',
        name: 'Hamburger',
        price: 5,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.5,
        imageUrl: 'images/food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '16',
        name: 'Fried Potatoes',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3.3,
        imageUrl: 'images/food-4.jpg',
        tags: ['FastFood', 'Fry'],
    },
    {
        id: '17',
        name: 'Chicken Soup',
        price: 11,
        cookTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.0,
        imageUrl: 'images/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
    },
    {
        id: '18',
        name: 'Vegetables Pizza',
        price: 9,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'images/food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '19',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'images/food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '20',
        name: 'Meatball',
        price: 20,
        cookTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        stars: 4.7,
        imageUrl: 'images/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
    },
    {
        id: '21',
        name: 'Hamburger',
        price: 5,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.5,
        imageUrl: 'images/food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '22',
        name: 'Fried Potatoes',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3.3,
        imageUrl: 'images/food-4.jpg',
        tags: ['FastFood', 'Fry'],
    },
    {
        id: '23',
        name: 'Chicken Soup',
        price: 11,
        cookTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.0,
        imageUrl: 'images/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
    },
    {
        id: '24',
        name: 'Vegetables Pizza',
        price: 9,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'images/food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '25',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'images/food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '26',
        name: 'Meatball',
        price: 20,
        cookTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        stars: 4.7,
        imageUrl: 'images/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
    },
    {
        id: '27',
        name: 'Hamburger',
        price: 5,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.5,
        imageUrl: 'images/food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '28',
        name: 'Fried Potatoes',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3.3,
        imageUrl: 'images/food-4.jpg',
        tags: ['FastFood', 'Fry'],
    },
    {
        id: '29',
        name: 'Chicken Soup',
        price: 11,
        cookTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.0,
        imageUrl: 'images/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
    },
    {
        id: '30',
        name: 'Vegetables Pizza',
        price: 9,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'images/food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '31',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'images/food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '32',
        name: 'Meatball',
        price: 20,
        cookTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        stars: 4.7,
        imageUrl: 'images/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
    },
    {
        id: '33',
        name: 'Hamburger',
        price: 5,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.5,
        imageUrl: 'images/food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '34',
        name: 'Fried Potatoes',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3.3,
        imageUrl: 'images/food-4.jpg',
        tags: ['FastFood', 'Fry'],
    },
    {
        id: '35',
        name: 'Chicken Soup',
        price: 11,
        cookTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.0,
        imageUrl: 'images/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
    },
    {
        id: '36',
        name: 'Vegetables Pizza',
        price: 9,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'images/food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '37',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'images/food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '38',
        name: 'Meatball',
        price: 20,
        cookTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        stars: 4.7,
        imageUrl: 'images/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
    },
    {
        id: '39',
        name: 'Hamburger',
        price: 5,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.5,
        imageUrl: 'images/food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '40',
        name: 'Fried Potatoes',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3.3,
        imageUrl: 'images/food-4.jpg',
        tags: ['FastFood', 'Fry'],
    },
    {
        id: '41',
        name: 'Chicken Soup',
        price: 11,
        cookTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.0,
        imageUrl: 'images/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
    },
    {
        id: '42',
        name: 'Vegetables Pizza',
        price: 9,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'images/food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '43',
        name: 'Vegetables Pizza',
        price: 9,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'images/food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '44',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'images/food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '45',
        name: 'Meatball',
        price: 20,
        cookTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        stars: 4.7,
        imageUrl: 'images/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
    },
    {
        id: '46',
        name: 'Hamburger',
        price: 5,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.5,
        imageUrl: 'images/food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '47',
        name: 'Fried Potatoes',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3.3,
        imageUrl: 'images/food-4.jpg',
        tags: ['FastFood', 'Fry'],
    },
    {
        id: '48',
        name: 'Chicken Soup',
        price: 11,
        cookTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.0,
        imageUrl: 'images/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
    },
    {
        id: '49',
        name: 'Vegetables Pizza',
        price: 9,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'images/food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '50',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'images/food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '51',
        name: 'Fried Potatoes',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3.3,
        imageUrl: 'images/food-4.jpg',
        tags: ['FastFood', 'Fry'],
    },
    {
        id: '52',
        name: 'Chicken Soup',
        price: 11,
        cookTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.0,
        imageUrl: 'images/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
    },
]

const sample_tags = [
    { name: 'All', count: 6 },
    { name: 'FastFood', count: 4 },
    { name: 'Pizza', count: 2 },
    { name: 'Lunch', count: 3 },
    { name: 'SlowFood', count: 2 },
    { name: 'Hamburger', count: 1 },
    { name: 'Fry', count: 1 },
    { name: 'Soup', count: 1 },
]

const sample_users = [
    {
        name: "Admin",
        email: "admin@gmail.com",
        password: "12345",
        address: "Toronto On",
        isAdmin: true,
    },
    {
        name: "User",
        email: "user@gmail.com",
        password: "12345",
        address: "Shanghai",
        isAdmin: false,
    },
    {
        name: "John",
        email: "john@gmail.com",
        password: "12345",
        address: "Toronto On",
        isAdmin: true,
    },
];

module.exports = {
    sample_food,
    sample_tags,
    sample_users
};
