const sample_food = [
    {
        id: '1',
        name: 'Pizza Pepperoni',
        description: 'Classic Italian pepperoni pizza with a crispy crust and cheesy topping.',
        deliveryTime: '10-20',
        price: 300,
        favorite: false,
        origins: ['italy'],
        rating: 4.5,
        discount: '₹175 OFF ABOVE 299',
        imageUrl: 'images/food/food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '2',
        name: 'Meatball',
        description: 'Juicy meatballs slow-cooked in rich tomato sauce, served hot and hearty.',
        price: 300,
        deliveryTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        rating: 4.7,
        discount: '',
        imageUrl: 'images/food/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
    },
    {
        id: '3',
        name: 'Hamburger',
        description: 'Grilled beef patty with lettuce, tomato, and cheese in a soft bun.',
        price: 250,
        deliveryTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        rating: 3.5,
        discount: '',
        imageUrl: 'images/food/food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '4',
        name: 'Fried Potatoes',
        description: 'Golden, crispy fried potatoes seasoned with herbs and served with dip.',
        price: 180,
        deliveryTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        rating: 3.3,
        discount: '₹15 OFF ABOVE 99',
        imageUrl: 'images/food/food-4.jpg',
        tags: ['FastFood', 'Fry'],
    },
    {
        id: '5',
        name: 'Chicken Soup',
        description: 'Comforting chicken broth with tender meat and aromatic spices.',
        price: 100,
        deliveryTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        rating: 3.0,
        discount: '',
        imageUrl: 'images/food/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
    },
    {
        id: '6',
        name: 'Vegetables Pizza',
        description: 'Loaded with fresh veggies, mozzarella cheese, and rich tomato sauce.',
        price: 250,
        deliveryTime: '40-50',
        favorite: false,
        origins: ['italy'],
        rating: 4.0,
        discount: '₹75 OFF ABOVE 199',
        imageUrl: 'images/food/food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '7',
        name: 'Margarita Pizza',
        description: 'Classic Margherita with fresh basil, tomato sauce, and melted cheese.',
        price: 350,
        deliveryTime: '45-50',
        favorite: false,
        origins: ['italy'],
        rating: 4.8,
        discount: '₹175 OFF ABOVE 349',
        imageUrl: 'images/pizza/pizza.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '8',
        name: 'Cheese Burger',
        description: 'Grilled beef burger topped with cheddar cheese and creamy sauces.',
        price: 250,
        deliveryTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        rating: 3.5,
        discount: '',
        imageUrl: 'images/food/food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '9',
        name: 'Hamburger',
        description: 'Classic hamburger with juicy meat patty and fresh veggies in a bun.',
        price: 250,
        deliveryTime: '30-35',
        favorite: false,
        origins: ['germany', 'us'],
        rating: 4.5,
        discount: '₹100 OFF ABOVE 249',
        imageUrl: 'images/pizza/burger-im-1.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '10',
        name: 'Burger With French Fries',
        description: 'Crispy fries paired with a classic burger for the perfect combo meal.',
        price: 250,
        deliveryTime: '20-25',
        favorite: false,
        origins: ['germany', 'us'],
        rating: 4.9,
        discount: '',
        imageUrl: 'images/pizza/burger-combo-img.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '11',
        name: 'Aloo Tikki Burger',
        description: 'Spicy aloo tikki with chutney and veggies in a soft Indian-style bun.',
        price: 100,
        deliveryTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        rating: 3.5,
        discount: '',
        imageUrl: 'images/pizza/burger-img-2.jpeg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '12',
        name: '7 Cheese Pizza',
        description: 'Indulgent pizza topped with a rich blend of 7 varieties of cheese.',
        price: 580,
        deliveryTime: '40-50',
        favorite: true,
        origins: ['italy'],
        rating: 4.9,
        discount: '₹175 OFF ABOVE 499',
        imageUrl: 'images/pizza/pizza-img-2.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '13',
        name: 'Paneer Tikka Pizza Small',
        description: 'Indian-style pizza topped with smoky paneer tikka and spicy sauce.',
        price: 280,
        deliveryTime: '40-50',
        favorite: true,
        origins: ['italy'],
        rating: 3.9,
        discount: '₹75 OFF ABOVE 279',
        imageUrl: 'images/pizza/pizza-img-3.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '14',
        name: 'Peri Peri Pizza',
        description: 'Fiery peri-peri sauce topped with veggies and loaded with cheese.',
        price: 480,
        deliveryTime: '40-50',
        favorite: true,
        origins: ['italy'],
        rating: 4.2,
        discount: '₹125 OFF ABOVE 479',
        imageUrl: 'images/pizza/pizza-img-4.webp',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    }
]

const sample_tags = [
    { name: 'All', count: 52 },
    { name: 'FastFood', count: 4 },
    { name: 'Pizza', count: 2 },
    { name: 'Lunch', count: 3 },
    { name: 'SlowFood', count: 2 },
    { name: 'Hamburger', count: 1 },
    { name: 'Fry', count: 1 },
    { name: 'Soup', count: 1 },
]

const sample_users = [
    {
        name: "Admin",
        email: "admin@gmail.com",
        password: "12345",
        address: "Toronto On",
        isAdmin: true,
    },
    {
        name: "User",
        email: "user@gmail.com",
        password: "12345",
        address: "Shanghai",
        isAdmin: false,
    },
    {
        name: "John",
        email: "john@gmail.com",
        password: "12345",
        address: "Toronto On",
        isAdmin: true,
    },
];

const categories = [
    {
        id: 1,
        name: 'Cakes',
        label: 'cakes',
        imageUrl: 'images/categories/cakes.png',
        description: 'Feast on amazing cakes to satisfy your sweet tooth.'
    },
    {
        id: 2,
        name: 'Desserts',
        label: 'desserts',
        imageUrl: 'images/categories/desserts.png',
        description: 'Feast on amazing desserts to satisfy your sweet tooth.'
    },
    {
        id: 3,
        name: 'Coffee',
        label: 'coffee',
        imageUrl: 'images/categories/coffee.png',
        description: 'Blaze through the day with a hot, steaming cup of coffee.'
    },
    {
        id: 4,
        name: 'Gulab Jamun',
        label: 'gulab-jamun',
        imageUrl: 'images/categories/gulab-jamun.png',
        description: 'Sweeten your day with these delicious and syrupy Gulab Jamuns.'
    },
    {
        id: 5,
        name: 'Lassi',
        label: 'lassi',
        imageUrl: 'images/categories/lassi.png',
        description: 'Rich & thick Lassis that will have you craving for more.'
    },
    {
        id: 6,
        name: 'Shake',
        label: 'shake',
        imageUrl: 'images/categories/shake.png',
        description: 'Tempt your taste buds with cold and thick milkshakes.'
    },
    {
        id: 7,
        name: 'Noodles',
        label: 'noodles',
        imageUrl: 'images/categories/noodles.png',
        description: 'Dive into these delicious & flavoursome noodles for a perfect meal.'
    },
    {
        id: 8,
        name: 'Poori',
        label: 'poori',
        imageUrl: 'images/categories/poori.png',
        description: 'A delicious, fried breakfast staple that will remind you of home.'
    },
    {
        id: 9,
        name: 'Chinese',
        label: 'chinese',
        imageUrl: 'images/categories/chinese.png',
        description: 'Transport your taste buds to the heart of Chinese cuisine with these scrumptious dishes.'
    },
    {
        id: 10,
        name: 'Chole Bhature',
        label: 'chole-bhature',
        imageUrl: 'images/categories/chole-bhature.png',
        description: 'Satisfy your cravings with these fluffy & flavoursome breads paired with Chole.'
    },
    {
        id: 11,
        name: 'Paratha',
        label: 'paratha',
        imageUrl: 'images/categories/paratha.png',
        description: 'Explore a wide variety of Parathas to satisfy your cravings.'
    },
    {
        id: 12,
        name: 'Pure Veg',
        label: 'pure-veg',
        imageUrl: 'images/categories/pure-veg.png',
        description: 'A vegetarian paradise loaded with options to satisfy your cravings.'
    },
    {
        id: 13,
        name: 'South Indian',
        label: 'south-indian',
        imageUrl: 'images/categories/south-indian.png',
        description: 'Explore hot & spicy dishes that are a specialty of South India.'
    },
];

const subcategories = [
    {
        id: 1,
        categoryId: '683071ab4b274ea0ea60220e',
        name: 'Special Cold Coffee',
        imageUrl: 'images/coffee/coffee-img-5.png',
        discount: '₹75 OFF ABOVE 199',
        rating: 4.2,
        deliveryTime: '45-55',
        price: 120,
        description: 'South Indian, Chinese, Fast Food, Beverages',
        location: 'Khajri Chowk',
    },
    {
        id: 2,
        categoryId: '683071ab4b274ea0ea60220e',
        name: 'Nes Cafe',
        imageUrl: 'images/coffee/coffee-img-3.png',
        discount: '₹50 OFF ABOVE ₹149',
        rating: 4.5,
        deliveryTime: '20-25',
        price: 100,
        description: 'Coffee, Snacks, Sandwiches, Beverages',
        location: 'City Center',
    },
    {
        id: 3,
        categoryId: '683071ab4b274ea0ea60220e',
        name: 'Cappuccino Coffee',
        imageUrl: 'images/coffee/coffee-img-2.jpg',
        discount: '₹100 OFF ABOVE ₹299',
        rating: 4.8,
        deliveryTime: '35-40',
        price: 130,
        description: 'Fast Food, Cold Coffee, Mocha',
        location: 'New Market',
    },
    {
        id: 4,
        categoryId: '683071ab4b274ea0ea60220e',
        name: 'Hot Coffee',
        imageUrl: 'images/coffee/coffee-img-4.png',
        discount: '₹50 OFF ABOVE ₹149',
        rating: 4.5,
        deliveryTime: '20-25',
        price: 90,
        description: 'Hot Chocolate, Coffee, Muffins',
        location: 'TT Nagar',
    },
    {
        id: 5,
        categoryId: '683071ab4b274ea0ea60220e',
        name: 'Cold Coffee',
        imageUrl: 'images/coffee/coffee-img-1.png',
        discount: '₹100 OFF ABOVE ₹299',
        rating: 4.8,
        deliveryTime: '35-40',
        price: 110,
        description: 'Hot Chocolate, Coffee, Muffins',
        location: 'TT Nagar',
    },
    {
        id: 6,
        categoryId: '683071ab4b274ea0ea60220f',
        name: 'Special Gulab Jambun',
        imageUrl: 'images/gulab-jambun/gulab-jambun-img-2.jpg',
        discount: '',
        rating: 4.8,
        deliveryTime: '10-15',
        price: 60,
        description: 'Sweet, Gulab Jambun, dinner',
        location: 'Khajri Chowk',
    },
    {
        id: 7,
        categoryId: '683071ab4b274ea0ea60220f',
        name: 'Kala Jambun',
        imageUrl: 'images/gulab-jambun/kala-gulab-jambun-img-5.webp',
        discount: '₹50 OFF ABOVE ₹149',
        rating: 4.5,
        deliveryTime: '20-25',
        price: 70,
        description: 'Lunch, Snacks, Sweet, Gulab Jambun',
        location: 'City Center',
    },
    {
        id: 8,
        categoryId: '683071ab4b274ea0ea60220f',
        name: 'Mawa Gulab Jambun',
        imageUrl: 'images/gulab-jambun/gulab-jambun-img-1.jpg',
        discount: '₹10 OFF ABOVE ₹199',
        rating: 4.3,
        deliveryTime: '15-25',
        price: 75,
        description: 'Sweet, Mawa, Jambun',
        location: 'New Market',
    },
    {
        id: 9,
        categoryId: '683071ab4b274ea0ea60220f',
        name: 'Anguri Gulab Jambun',
        imageUrl: 'images/gulab-jambun/gulab-jambun-img-3.webp',
        discount: '',
        rating: 3.5,
        deliveryTime: '10-15',
        price: 65,
        description: 'Lunch, Snacks, Sweet, Gulab Jambun',
        location: 'TT Nagar',
    },
    {
        id: 10,
        categoryId: '683071ab4b274ea0ea60220f',
        name: 'Gulab Jambun',
        imageUrl: 'images/gulab-jambun/gulab-jambun-img-4.webp',
        discount: '',
        rating: 4.8,
        deliveryTime: '5-10',
        price: 55,
        description: 'Lunch, Snacks, Sweet, Gulab Jambun',
        location: 'TT Nagar',
    },
    {
        id: 11,
        categoryId: '683071ab4b274ea0ea60220d',
        name: 'Chocolate Brownies',
        imageUrl: 'images/desserts/desserts-img-1.jpg',
        discount: '₹10 OFF ABOVE ₹199',
        rating: 4.8,
        deliveryTime: '15-20',
        price: 90,
        description: 'Rich and fudgy chocolate brownies made with premium cocoa, baked to perfection with a crisp top and gooey center. Ideal for satisfying your sweet cravings.',
        location: 'TT Nagar',
    },
    {
        id: 12,
        categoryId: '683071ab4b274ea0ea60220d',
        name: 'Macaroons',
        imageUrl: 'images/desserts/desserts-img-2.jpg',
        discount: '',
        rating: 4.0,
        deliveryTime: '20-25',
        price: 120,
        description: 'Colorful and delicate French macaroons with a crisp shell and soft, chewy center. Lightly sweetened and filled with a creamy ganache or buttercream',
        location: 'Khajri Chowk',
    },
    {
        id: 13,
        categoryId: '683071ab4b274ea0ea60220d',
        name: 'Chocolate Cake',
        imageUrl: 'images/desserts/desserts-img-3.jpg',
        discount: '₹50 OFF ABOVE ₹149',
        rating: 4.5,
        deliveryTime: '20-25',
        price: 150,
        description: 'Decadent chocolate cake layered with rich chocolate ganache. Moist, fluffy, and intensely chocolaty — perfect for celebrations or indulgent treats.',
        location: 'City Center',
    },
    {
        id: 14,
        categoryId: '683071ab4b274ea0ea60220d',
        name: 'Chocolate Brownies (New Market)',
        imageUrl: 'images/desserts/desserts-img-4.jpg',
        discount: '₹20 OFF ABOVE ₹199',
        rating: 4.3,
        deliveryTime: '35-40',
        price: 100,
        description: 'Dense, melt-in-your-mouth chocolate brownies served warm. A timeless dessert made with premium dark chocolate and a touch of vanilla.',
        location: 'New Market',
    },
    {
        id: 15,
        categoryId: '683071ab4b274ea0ea60220d',
        name: 'Chocolate with Ice Cream',
        imageUrl: 'images/desserts/desserts-img-5.jpg',
        discount: '₹50 OFF ABOVE ₹149',
        rating: 3.5,
        deliveryTime: '20-25',
        price: 130,
        description: 'A luscious combo of warm chocolate cake topped with a scoop of creamy vanilla ice cream and drizzled with chocolate syrup. A dessert lover’s dream!',
        location: 'TT Nagar',
    },
    {
        id: 16,
        categoryId: '683071ab4b274ea0ea60220c',
        name: 'Chocolate Pastry',
        imageUrl: 'images/desserts/desserts-img-3.jpg',
        discount: '₹50 OFF ABOVE ₹149',
        rating: 4.5,
        deliveryTime: '20-25',
        price: 70,
        description: 'Decadent chocolate cake layered with rich chocolate ganache. Moist, fluffy, and intensely chocolaty — perfect for celebrations or indulgent treats.',
        location: 'City Center',
    },
    {
        id: 17,
        categoryId: '683071ab4b274ea0ea60220c',
        name: 'Chocolate Cake',
        imageUrl: 'images/cake/cake-img-1.webp',
        discount: '',
        rating: 3.5,
        deliveryTime: '20-25',
        price: 160,
        description: 'A luscious combo of warm chocolate cake topped with a scoop of creamy vanilla ice cream and drizzled with chocolate syrup. A dessert lover’s dream!',
        location: 'TT Nagar',
    },
    {
        id: 18,
        categoryId: '683071ab4b274ea0ea60220c',
        name: 'Dark Chocolate Cake',
        imageUrl: 'images/cake/cake-img-2.jpeg',
        discount: '',
        rating: 4.5,
        deliveryTime: '20-25',
        price: 170,
        description: 'Decadent chocolate cake layered with rich chocolate ganache. Moist, fluffy, and intensely chocolaty — perfect for celebrations or indulgent treats.',
        location: 'New Market',
    },
    {
        id: 19,
        categoryId: '683071ab4b274ea0ea60220c',
        name: 'Black Forest Cake',
        imageUrl: 'images/cake/cake-img-4.webp',
        discount: '₹50 OFF ABOVE ₹149',
        rating: 3.5,
        deliveryTime: '20-25',
        price: 160,
        description: 'A luscious combo of warm chocolate cake topped with a scoop of creamy vanilla ice cream and drizzled with chocolate syrup. A dessert lover’s dream!',
        location: 'TT Nagar',
    },
    {
        id: 20,
        categoryId: '683071ab4b274ea0ea60220c',
        name: 'Red Velvet Cake',
        imageUrl: 'images/cake/cake-img-5.webp',
        discount: '',
        rating: 4.0,
        deliveryTime: '20-25',
        price: 165,
        description: 'A luscious combo of warm chocolate cake topped with a scoop of creamy vanilla ice cream and drizzled with chocolate syrup. A dessert lover’s dream!',
        location: 'New Market',
    },
    {
        id: 21,
        categoryId: '683071ab4b274ea0ea60220c',
        name: 'Chocolate Cake',
        imageUrl: 'images/cake/cake-img-3.webp',
        discount: '',
        rating: 4.5,
        deliveryTime: '20-25',
        price: 160,
        description: 'Decadent chocolate cake layered with rich chocolate ganache. Moist, fluffy, and intensely chocolaty — perfect for celebrations or indulgent treats.',
        location: 'City Center',
    },
    {
        id: 22,
        categoryId: '683071ab4b274ea0ea602211',
        name: 'Chocolate Cake Shake',
        imageUrl: 'images/shake/shake-img-1.jpg',
        discount: '₹15 OFF ABOVE ₹149',
        rating: 3.5,
        deliveryTime: '10-15',
        price: 130,
        description: 'A dreamy fusion of thick milkshake and moist chocolate cake! Perfectly sweet, satisfyingly creamy — every sip is a dessert lover’s fantasy.',
        location: 'TT Nagar',
    },
    {
        id: 23,
        categoryId: '683071ab4b274ea0ea602211',
        name: 'Strawberry Shake',
        imageUrl: 'images/shake/shake-img-2.webp',
        discount: '₹10 OFF ABOVE ₹149',
        rating: 3.9,
        deliveryTime: '20-25',
        price: 120,
        description: 'A creamy, fruity blend of fresh strawberries and milk, perfect for a refreshing treat.',
        location: 'TT Nagar',
    },
    {
        id: 24,
        categoryId: '683071ab4b274ea0ea602211',
        name: 'Chocolate Milk Shake',
        imageUrl: 'images/shake/shake-img-3.jpg',
        discount: '₹15 OFF ABOVE ₹149',
        rating: 3.5,
        deliveryTime: '10-15',
        price: 120,
        description: 'A rich and creamy blend of chocolate ice cream and milk, crafted for ultimate indulgence.',
        location: 'City Center',
    },
    {
        id: 25,
        categoryId: '683071ab4b274ea0ea602211',
        name: 'Mango Milk Shake',
        imageUrl: 'images/shake/shake-img-4.jpg',
        discount: '',
        rating: 3.5,
        deliveryTime: '30-35',
        price: 110,
        description: 'A smooth and refreshing blend of ripe mangoes and chilled milk for a tropical delight.',
        location: 'New Market',
    },
    {
        id: 26,
        categoryId: '683071ab4b274ea0ea602211',
        name: 'Banana Milk Shake With Ice Cream',
        imageUrl: 'images/shake/shake-img-5.jpg',
        discount: '₹10 OFF ABOVE ₹149',
        rating: 4.9,
        deliveryTime: '20-25',
        price: 130,
        description: 'A creamy fusion of ripe bananas, chilled milk, and a scoop of ice cream for a naturally sweet treat.',
        location: 'TT Nagar',
    },
    {
        id: 27,
        categoryId: '683071ab4b274ea0ea602211',
        name: 'Vanilla Milk Shake',
        imageUrl: 'images/shake/shake-img-6.jpg',
        discount: '₹15 OFF ABOVE ₹149',
        rating: 4.5,
        deliveryTime: '10-15',
        price: 115,
        description: 'A classic, smooth blend of creamy vanilla ice cream and chilled milk for a timeless treat.',
        location: 'New Market',
    },
    {
        id: 28,
        categoryId: '683071ab4b274ea0ea602211',
        name: 'Kit Kat Milk Shake',
        imageUrl: 'images/shake/shake-img-7.jpg',
        discount: '₹15 OFF ABOVE ₹149',
        rating: 3.5,
        deliveryTime: '10-15',
        price: 135,
        description: 'A crunchy, creamy delight made with crushed Kit Kat bars, rich chocolate, and chilled milk.',
        location: 'New Market',
    },
    {
        id: 29,
        categoryId: '683071ab4b274ea0ea602212',
        name: 'Egg-Fried Noodles',
        imageUrl: 'images/noodles/noodles-img-1.webp',
        discount: '₹15 OFF ABOVE ₹149',
        rating: 3.5,
        deliveryTime: '15-25',
        price: 140,
        description: 'A savory stir-fry of springy noodles tossed with scrambled eggs and aromatic seasonings.',
        location: 'New Market',
    },
    {
        id: 30,
        categoryId: '683071ab4b274ea0ea602212',
        name: 'Soy Sauce Pan-fried Noodles',
        imageUrl: 'images/noodles/noodles-img-2.webp',
        discount: '',
        rating: 4.5,
        deliveryTime: '20-25',
        price: 150,
        description: 'Crispy-edged noodles flash-fried in rich soy sauce with garlic and a hint of sesame.',
        location: 'New Market',
    },
    {
        id: 31,
        categoryId: '683071ab4b274ea0ea602212',
        name: 'Vegetable Noodles',
        imageUrl: 'images/noodles/noodles-img-3.jpg',
        discount: '₹15 OFF ABOVE ₹149',
        rating: 4.5,
        deliveryTime: '20-35',
        price: 130,
        description: `Colorful garden veggies and tender noodles wok-tossed in a light, flavorful sauce.`,
        location: 'New Market',
    },
    {
        id: 32,
        categoryId: '683071ab4b274ea0ea602212',
        name: 'Hakka Noodles',
        imageUrl: 'images/noodles/noodles-img-4.webp',
        discount: '₹20 OFF ABOVE ₹119',
        rating: 4.5,
        deliveryTime: '20-25',
        price: 135,
        description: `Springy wok-tossed noodles stir-fried with crunchy vegetables, soy-based sauces, and aromatic spices.`,
        location: 'New Market',
    },
    {
        id: 33,
        categoryId: '683071ab4b274ea0ea602213',
        name: 'Poori',
        imageUrl: 'images/poori/poori-img-1.jpg',
        discount: '',
        rating: 4.5,
        deliveryTime: '25-30',
        price: 90,
        description: `Light, fluffy deep-fried wheat bread that's golden and puffed—perfect for pairing with curries or chutneys.`,
        location: 'New Market',
    },
    {
        id: 34,
        categoryId: '683071ab4b274ea0ea602210',
        name: 'Homemade Sweet Lassi',
        imageUrl: 'images/lassi/lassi-img-7.webp',
        discount: '',
        rating: 5.0,
        deliveryTime: '15-20',
        price: 60,
        description: `A classic blend of creamy yogurt and sugar, served chilled for a refreshing homemade treat.`,
        location: 'New Market',
    },
    {
        id: 35,
        categoryId: '683071ab4b274ea0ea602210',
        name: 'Kesar Lassi',
        imageUrl: 'images/lassi/lassi-img-1.webp',
        discount: '₹30 OFF ABOVE ₹299',
        rating: 4.5,
        deliveryTime: '25-30',
        price: 90,
        description: `A rich and aromatic lassi infused with saffron strands for a royal flavor.`,
        location: 'New Market',
    },
    {
        id: 36,
        categoryId: '683071ab4b274ea0ea602210',
        name: 'Mango Lassi',
        imageUrl: 'images/lassi/lassi-img-2.png',
        discount: '₹20 OFF ABOVE ₹199',
        rating: 4.9,
        deliveryTime: '25-30',
        price: 80,
        description: `A fruity and creamy yogurt drink blended with ripe mangoes for a tropical twist.`,
        location: 'New Market',
    },
    {
        id: 37,
        categoryId: '683071ab4b274ea0ea602210',
        name: 'Malai Lassi',
        imageUrl: 'images/lassi/lassi-img-3.png',
        discount: '',
        rating: 4.1,
        deliveryTime: '25-30',
        price: 85,
        description: `A thick, indulgent lassi topped with a layer of fresh malai (cream) for extra richness.`,
        location: 'New Market',
    },
    {
        id: 38,
        categoryId: '683071ab4b274ea0ea602210',
        name: 'Special Lassi',
        imageUrl: 'images/lassi/lassi-img-4.png',
        discount: '₹10 OFF ABOVE ₹199',
        rating: 5.0,
        deliveryTime: '15-20',
        price: 95,
        description: `A flavorful, creamy delight made with a secret mix of traditional ingredients for a unique taste.`,
        location: 'New Market',
    },
    {
        id: 39,
        categoryId: '683071ab4b274ea0ea602210',
        name: 'Punjabi Lassi',
        imageUrl: 'images/lassi/lassi-img-5.jpg',
        discount: '₹10 OFF ABOVE ₹299',
        rating: 4.5,
        deliveryTime: '25-30',
        price: 90,
        description: `A thick, frothy, and ultra-creamy yogurt drink straight from the heart of Punjab.`,
        location: 'New Market',
    },
    {
        id: 40,
        categoryId: '683071ab4b274ea0ea602210',
        name: 'Sweet Lassi',
        imageUrl: 'images/lassi/lassi-img-6.jpg',
        discount: '₹20 OFF ABOVE ₹199',
        rating: 4.9,
        deliveryTime: '25-30',
        price: 70,
        description: `A simple and soothing yogurt-based drink sweetened to perfection and served ice cold.`,
        location: 'New Market',
    },
    {
        id: 41,
        categoryId: '683071ab4b274ea0ea602214',
        name: 'Egg-Fried Noodles',
        imageUrl: 'images/noodles/noodles-img-1.webp',
        discount: '₹15 OFF ABOVE ₹149',
        rating: 3.5,
        deliveryTime: '15-25',
        price: 129,
        description: 'A savory stir-fry of springy noodles tossed with scrambled eggs and aromatic seasonings.',
        location: 'New Market',
    },
    {
        id: 42,
        categoryId: '683071ab4b274ea0ea602214',
        name: 'Soy Sauce Pan-fried Noodles',
        imageUrl: 'images/noodles/noodles-img-2.webp',
        discount: '',
        rating: 4.5,
        deliveryTime: '20-25',
        price: 129,
        description: 'Crispy-edged noodles flash-fried in rich soy sauce with garlic and a hint of sesame.',
        location: 'New Market',
    },
    {
        id: 43,
        categoryId: '683071ab4b274ea0ea602214',
        name: 'Vegetable Noodles',
        imageUrl: 'images/noodles/noodles-img-3.jpg',
        discount: '₹15 OFF ABOVE ₹149',
        rating: 4.5,
        deliveryTime: '20-35',
        price: 129,
        description: 'Colorful garden veggies and tender noodles wok-tossed in a light, flavorful sauce.',
        location: 'New Market',
    },
    {
        id: 44,
        categoryId: '683071ab4b274ea0ea602214',
        name: 'Hakka Noodles',
        imageUrl: 'images/noodles/noodles-img-4.webp',
        discount: '₹20 OFF ABOVE ₹119',
        rating: 4.5,
        deliveryTime: '20-25',
        price: 129,
        description: 'Springy wok-tossed noodles stir-fried with crunchy vegetables, soy-based sauces, and aromatic spices.',
        location: 'New Market',
    },
    {
        id: 45,
        categoryId: '683071ab4b274ea0ea602215',
        name: 'Chole Bhature',
        imageUrl: 'images/chole-bhature/chole-bhature-img-1.jpg',
        discount: '₹30 OFF ABOVE ₹299',
        rating: 4.5,
        deliveryTime: '25-30',
        price: 159,
        description: 'A flavorful combo of spicy chickpeas and deep-fried, fluffy bhature—a North Indian favorite.',
        location: 'New Market',
    },
    {
        id: 46,
        categoryId: '683071ab4b274ea0ea602215',
        name: 'Isanpur Wala Chole Bhature',
        imageUrl: 'images/chole-bhature/chole-bhature-img-2.webp',
        discount: '₹30 OFF ABOVE ₹299',
        rating: 4.5,
        deliveryTime: '25-30',
        price: 159,
        description: 'Signature-style chole bhature from Inshanpur, known for its bold spices and authentic taste.',
        location: 'New Market',
    },
    {
        id: 47,
        categoryId: '683071ab4b274ea0ea602215',
        name: 'Delhi Wale Chole Bhature',
        imageUrl: 'images/chole-bhature/chole-bhature-north-img-3.webp',
        discount: '₹20 OFF ABOVE ₹199',
        rating: 4.9,
        deliveryTime: '25-30',
        price: 169,
        description: 'Delhi’s iconic version of chole bhature, rich in flavor and served with tangy pickle and onions.',
        location: 'New Market',
    },
    {
        id: 48,
        categoryId: '683071ab4b274ea0ea602216',
        name: 'Aloo Paratha',
        imageUrl: 'images/paratha/aloo-paratha-img-1.webp',
        discount: '₹75 OFF ABOVE 199',
        rating: 4.2,
        deliveryTime: '45-55',
        price: 99,
        description: 'A stuffed flatbread filled with spiced mashed potatoes, pan-fried to golden perfection.',
        location: 'Khajri Chowk',
    },
    {
        id: 49,
        categoryId: '683071ab4b274ea0ea602216',
        name: 'Paratha',
        imageUrl: 'images/paratha/aloo-paratha-img-2.jpg',
        discount: '₹50 OFF ABOVE ₹149',
        rating: 4.5,
        deliveryTime: '20-25',
        price: 89,
        description: 'A flaky, buttery Indian flatbread, crisp on the outside and soft within.',
        location: 'City Center',
    },
    {
        id: 50,
        categoryId: '683071ab4b274ea0ea602216',
        name: 'Dahi Paratha',
        imageUrl: 'images/paratha/aloo-paratha-img-3.jpg',
        discount: '₹20 OFF ABOVE ₹199',
        rating: 4.9,
        deliveryTime: '25-30',
        price: 109,
        description: 'A flavorful paratha served with or infused with tangy curd for a refreshing twist.',
        location: 'New Market',
    },
    {
        id: 51,
        categoryId: '683071ab4b274ea0ea602217',
        name: 'Pure Veg Meal',
        imageUrl: 'images/pure-veg/pure-veg-meal-img-1.png',
        discount: '₹100 OFF ABOVE ₹299',
        rating: 4.8,
        deliveryTime: '35-40',
        price: 229,
        description: 'A wholesome and satisfying meal featuring a variety of flavorful vegetarian dishes, perfect for a complete traditional experience.',
        location: 'TT Nagar',
    },
    {
        id: 52,
        categoryId: '683071ab4b274ea0ea602218',
        name: 'South Indian Special Meal',
        imageUrl: 'images/south-indian/south-indian-meal-img-1.jpg',
        discount: '',
        rating: 4.8,
        deliveryTime: '40-45',
        price: 199,
        description: 'A delicious assortment of authentic South Indian dishes served on a platter, offering a perfect balance of flavors and tradition.',
        location: 'Khajri Chowk',
    },
    {
        id: 53,
        categoryId: '683071ab4b274ea0ea602218',
        name: 'Masala Dosa',
        imageUrl: 'images/south-indian/masala-dosa-img-3.jpg',
        discount: '',
        rating: 4.5,
        deliveryTime: '20-25',
        price: 109,
        description: 'A crispy, golden dosa filled with spiced mashed potatoes, served with chutneys and sambar for a flavorful South Indian treat.',
        location: 'City Center',
    },
    {
        id: 52,
        categoryId: '683071ab4b274ea0ea602218',
        name: 'Idli Sambhar',
        imageUrl: 'images/south-indian/idli-sambhar-img-2.jpg',
        discount: '',
        rating: 4.8,
        deliveryTime: '40-45',
        price: 99,
        description: 'A delicious assortment of authentic South Indian dishes served on a platter, offering a perfect balance of flavors and tradition.',
        location: 'Khajri Chowk',
    },
    {
        id: 53,
        categoryId: '683071ab4b274ea0ea602218',
        name: 'Idli Sambhar - Mendu Vada Meal',
        imageUrl: 'images/south-indian/idli-sambhar-mendu-vada-img-1.jpg',
        discount: '',
        rating: 4.5,
        deliveryTime: '20-25',
        price: 119,
        description: 'A hearty South Indian combo of soft idlis, crispy medu vadas, and flavorful sambar served with coconut chutney.',
        location: 'City Center',
    },
    {
        id: 54,
        categoryId: '683071ab4b274ea0ea602218',
        name: 'Gotado Dosa',
        imageUrl: 'images/south-indian/gotadao-dosa-img-4.jpg',
        discount: '',
        rating: 4.5,
        deliveryTime: '20-25',
        price: 109,
        description: 'A crispy dosa with a unique twist, filled with spiced potato masala and folded for a satisfying bite every time.',
        location: 'TT Nagar',
    }
];

module.exports = {
    sample_food,
    sample_tags,
    sample_users,
    categories,
    subcategories
};