import { Food } from "./app/shared/models/food";

export const sample_food: Food[] = [
    {
        id: '1',
        name: 'Coffee',
        deliveryTime: '5-10',
        price: 10,
        favorite: true,
        origins: ['italy', 'ethiopia', 'brazil'],
        rating: 4.5,
        imageUrl: 'images/foodCategories/coffee-img-2.jpg',
        tags: ['',],
    },
    {
        id: '2',
        name: 'Meatball',
        price: 20,
        deliveryTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        rating: 4.7,
        imageUrl: 'images/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
    },
    {
        id: '3',
        name: 'Hamburger',
        price: 5,
        deliveryTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        rating: 3.5,
        imageUrl: 'images/food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '4',
        name: 'Fried Potatoes',
        price: 2,
        deliveryTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        rating: 3.3,
        imageUrl: 'images/food-4.jpg',
        tags: ['FastFood', 'Fry'],
    },
    {
        id: '5',
        name: 'Chicken Soup',
        price: 11,
        deliveryTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        rating: 3.0,
        imageUrl: 'images/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
    },
    {
        id: '6',
        name: 'Vegetables Pizza',
        price: 9,
        deliveryTime: '40-50',
        favorite: false,
        origins: ['italy'],
        rating: 4.0,
        imageUrl: 'images/food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
]

export const food_categories = [
    { id: 1, name: 'Cakes', label: 'cakes', img: 'images/foodCategories/cakes.png', description: 'Feast on amazing cakes to satisfy your sweet tooth.' },
    { id: 2, name: 'Desserts', label: 'desserts', img: 'images/foodCategories/desserts.png', description: 'Feast on amazing desserts to satisfy your sweet tooth.' },
    { id: 3, name: 'Coffee', label: 'coffee', img: 'images/foodCategories/coffee.png', description: 'Blaze through the day with a hot, steaming cup of coffee.' },
    { id: 4, name: 'Gulab Jamun', label: 'gulab-jamun', img: 'images/foodCategories/gulab-jamun.png', description: 'Sweeten your day with these delicious and syrupy Gulab Jamuns.' },
    { id: 5, name: 'Lassi', label: 'lassi', img: 'images/foodCategories/lassi.png', description: 'Rich & thick Lassis that will have you craving for more.' },
    { id: 6, name: 'Shake', label: 'shake', img: 'images/foodCategories/shake.png', description: 'Tempt your taste buds with cold and thick milkshakes.' },
    { id: 7, name: 'Noodles', label: 'noodles', img: 'images/foodCategories/noodles.png', description: 'Dive into these delicious & flavoursome noodles for a perfect meal.' },
    { id: 8, name: 'Poori', label: 'poori', img: 'images/foodCategories/poori.png', description: 'A delicious, fried breakfast staple that will remind you of home.' },
    { id: 9, name: 'Chinese', label: 'chinese', img: 'images/foodCategories/chinese.png', description: 'Transport your taste buds to the heart of Chinese cuisine with these scrumptious dishes.' },
    { id: 10, name: 'Chole Bhature', label: 'chole-bhature', img: 'images/foodCategories/chole-bhature.png', description: 'Satisfy your cravings with these fluffy & flavoursome breads paired with Chole.' },
    { id: 11, name: 'Paratha', label: 'paratha', img: 'images/foodCategories/paratha.png', description: 'Explore a wide variety of Parathas to satisfy your cravings.' },
    { id: 12, name: 'Pure Veg', label: 'pure-veg', img: 'images/foodCategories/pure-veg.png', description: 'A vegetarian paradise loaded with options to satisfy your cravings.' },
    { id: 13, name: 'South Indian', label: 'south-indian', img: 'images/foodCategories/south-indian.png', description: 'Explore hot & spicy dishes that are a specialty of South India.' },
];

export const subcategories  = [
    { id: 1, name: 'Special Cold Coffee', label: 'coffee', img: 'images/coffee/coffee-img-5.png', discount: '₹50 OFF ABOVE ₹349', description: 'Feast on amazing cakes to satisfy your sweet tooth.' },
    { id: 2, name: 'Nes Cafe', label: 'desserts', img: 'images/foodCategories/desserts.png', description: 'Feast on amazing desserts to satisfy your sweet tooth.' },
    { id: 3, name: 'Cappuccino Coffee', label: 'coffee', img: 'images/foodCategories/coffee.png', description: 'Blaze through the day with a hot, steaming cup of coffee.' },
    { id: 4, name: 'Hot Coffee', label: 'gulab-jamun', img: 'images/foodCategories/gulab-jamun.png', description: 'Sweeten your day with these delicious and syrupy Gulab Jamuns.' },
    { id: 5, name: 'Cold Coffee', label: 'lassi', img: 'images/foodCategories/lassi.png', description: 'Rich & thick Lassis that will have you craving for more.' },
    { id: 6, name: 'Shake', label: 'shake', img: 'images/foodCategories/shake.png', description: 'Tempt your taste buds with cold and thick milkshakes.' },
    { id: 7, name: 'Noodles', label: 'noodles', img: 'images/foodCategories/noodles.png', description: 'Dive into these delicious & flavoursome noodles for a perfect meal.' },
    { id: 8, name: 'Poori', label: 'poori', img: 'images/foodCategories/poori.png', description: 'A delicious, fried breakfast staple that will remind you of home.' },
    { id: 9, name: 'Chinese', label: 'chinese', img: 'images/foodCategories/chinese.png', description: 'Transport your taste buds to the heart of Chinese cuisine with these scrumptious dishes.' },
    { id: 10, name: 'Chole Bhature', label: 'chole-bhature', img: 'images/foodCategories/chole-bhature.png', description: 'Satisfy your cravings with these fluffy & flavoursome breads paired with Chole.' },
    { id: 11, name: 'Paratha', label: 'paratha', img: 'images/foodCategories/paratha.png', description: 'Explore a wide variety of Parathas to satisfy your cravings.' },
    { id: 12, name: 'Pure Veg', label: 'pure-veg', img: 'images/foodCategories/pure-veg.png', description: 'A vegetarian paradise loaded with options to satisfy your cravings.' },
    { id: 13, name: 'South Indian', label: 'south-indian', img: 'images/foodCategories/south-indian.png', description: 'Explore hot & spicy dishes that are a specialty of South India.' },
];

export const sample_tags = [
    { name: 'All', count: 6 },
    { name: 'FastFood', count: 4 },
    { name: 'Pizza', count: 2 },
    { name: 'Lunch', count: 3 },
    { name: 'SlowFood', count: 2 },
    { name: 'Hamburger', count: 1 },
    { name: 'Fry', count: 1 },
    { name: 'Soup', count: 1 },
]