const HTTP_BAD_REQUEST = 400;
const HTTP_UNAUTHORIZED = 401;
const HTTP_SUCCESS_REQUEST = 200;
const HTTP_INTERNAL_SERVER_ERROR = 500;

module.exports = { HTTP_BAD_REQUEST, HTTP_UNAUTHORIZED, HTTP_SUCCESS_REQUEST, HTTP_INTERNAL_SERVER_ERROR };